Repository paperwm/PaperWM, pull requests merged in 2023-10, with the labels that each got.

#616 Fix opening application animation glitches
  stylesheet.css
  tiling.js
  topbar.js
Labels: merging soon

#614 FIXES: minimap sizing and label placements
  minimap.js
Labels: merging soon

#621 Allow user to change the percent of workspace width `Super+F` (maximize window takes)
  README.md
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  tiling.js
Labels: merging soon

#624 Fix gnome pill (indicator) workspace switch animation and improve PaperWM switching animations
  patches.js
  tiling.js
Labels: merging soon, gnome-45

#625 Backport of improve-gnome-pill-behaviour from gnome-45 (improves animations / some visuals)
  examples/keybindings.js
  navigator.js
  patches.js
  stackoverlay.js
  tiling.js
Labels: testing-requested

#633 Fix #631 take window clickoverlay lose control (fix for Gnome 42-44)
  navigator.js
  settings.js
  stackoverlay.js
  tiling.js
  topbar.js
Labels: merging soon

#618 Fix #617 resizing windows beyond space boundaries (in multimonitor setup) leads to inconsistent state
  Settings.ui
  grab.js
  navigator.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  stackoverlay.js
  tiling.js
Labels: bug, help wanted, multi-monitors, testing-requested

#639 Fix #617 resize windows beyond space (for Gnome 45)
  grab.js
  navigator.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  stackoverlay.js
  tiling.js
Labels: merging soon

#641 Fix 638 fullscreen animation window resize bug
  Settings.ui
  tiling.js
  utils.js
Labels: merging soon

#645 Add keybindings to switch to ws from all monitors
  README.md
  keybindings.js
  prefsKeybinding.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  tiling.js
Labels: merging soon
