Repository paperwm/PaperWM, pull requests merged in 2023-05, with the labels that each got.

#515 Fixes: add Gnome 44 support
  README.md
  grab.js
  keybindings.js
  kludges.js
  metadata.json
  navigator.js
  set-recommended-gnome-shell-settings.sh
  settings.js
  tiling.js
  utils.js
Labels: merging soon, gnome-44

#530 Fixes: keybind clash detection also correctly detects `grave` against mutter `Above_Tab`. Fix keybind replace.
  README.md
  settings.js
Labels: merging soon

#532 Generate restore script with second timestamp
  set-recommended-gnome-shell-settings.sh
Labels: merging soon

#539 REGRESSION FIX: Gnome 44 backported keybind fixes broke Gnome 43 (and earlier) keybind clash detection
  settings.js
Labels: gnome-42, merging soon, gnome-43

#540 Improve compatibility with previous gnome versions in `develop` branch
  settings.js
Labels: merging soon
