Repository paperwm/PaperWM, pull requests merged in 2023-11, with the labels that each got.

#660 Added touch support to multi-monitor switching
  stackoverlay.js
Labels: multi-monitors

#670 Add gnome media-keys schema to conflict checking
  settings.js
Labels: merging soon

#678 Fix #671: ensure window is in a focusable/resizable state before window shown
  tiling.js
Labels: merging soon

#679 Feature 526 open new window position gnome45
  Settings.ui
  prefs.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  tiling.js
Labels: merging soon

#480 Add CONTRIBUTING.md with basic history and outline
  CONTRIBUTING.md
Labels: merging soon

#687 Add keybindings to switch to ws from all monitors
  README.md
  keybindings.js
  prefsKeybinding.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  tiling.js
Labels: merging soon

#686 FIX 684 - windows change their horizontal position after consuming operation
  tiling.js
Labels: merging soon

#697 Fix 682 tiling gesture can break on gnome workspace switching
  gestures.js
  metadata.json
  tiling.js
Labels: merging soon

#698 Fix 682 tiling gesture can break on gnome workspace switching (for Gnome 44)
  gestures.js
  tiling.js
Labels: gnome-42, merging soon, gnome-44, gnome-43, testing-requested

#705 Add advanced settings tab in preferences (with other PaperWM settings)
  README.md
  Settings.ui
  gestures.js
  media/default-focus-mode.png
  media/gesture-settings.png
  media/topbar-styling.png
  media/window-indicator-bar.png
  prefs.js
  topbar.js
Labels: merging soon

#717 Update GitHub issues submission and README.md to reference GitHub Discussion (and not zulip)
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: merging soon

#715 Enhancement #672: allow users to change overview exit transition animation
  Settings.ui
  metadata.json
  patches.js
  prefs.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  tiling.js
Labels: merging soon
