Repository paperwm/PaperWM, pull requests merged in 2023-06, with the labels that each got.

#531 FIX: issue 136 (super+esc confusion when user is in navigator)
  navigator.js
Labels: merging soon

#542 Updated README.md and combined gnome versions targeted for current support.
  README.md
Labels: documentation, merging soon

#535 FIX: "taking" windows (e.g. by Super+T or by Ctrl+Super+`) now keeps that window selected/activated on target workspace
  keybindings.js
  tiling.js
Labels: merging soon

#543 FIX: for multimonitor setups where the non-primary monitor topbar initially shows focus mode icon position incorrectly
  tiling.js
  topbar.js
Labels: multi-monitors, merging soon

#510 Add option to allow all keybindings in the navigator
  navigator.js
  tiling.js
Labels: merging soon

#548 FIX: workspace label can be mis-positioned in stack/sequence workspace switching
  tiling.js
  topbar.js
Labels: merging soon

#546 Dim tiled windows when a non-tiled window (including transient windows) is focused
  grab.js
  navigator.js
  tiling.js
Labels: merging soon

#544 Multi-monitor support improvements. Deprecates `Make topbar follow monitor focus`
  Settings.ui
  prefs.js
  schemas/gschemas.compiled
  schemas/org.gnome.shell.extensions.paperwm.gschema.xml
  settings.js
  tiling.js
  topbar.js
Labels: multi-monitors, merging soon, seeking-feedback

#550 Support setting a default window property rule
  README.md
  WinpropsRow.ui
  media/default-star-winprop.png
  settings.js
  topbar.js
Labels: merging soon

#551 Behaviour_change: when selecting transient windows, do NOT drag view back to tiled parent
  tiling.js
Labels: merging soon, seeking-feedback

#552 Use 3-finger swipe-up for gnome overview and 3-finger swipe-down for PaperWM workspace stack tiling preview
  gestures.js
  kludges.js
  tiling.js
Labels: merging soon, seeking-feedback

#553 FIX: hold notifications when current window is fullscreen (Notifications are then shown when the window is un-fullscreened)
  kludges.js
Labels: merging soon

#554 Preparation to move default branch from `develop` to `release` branch
  README.md
Labels: seeking-feedback
